CREATE TABLE [dbo].[TransactionHistory] (
    [TransactionHistoryID]               INT             IDENTITY (1, 1) NOT NULL,
    [ID]                                 INT             NULL,
    [User]                               VARCHAR (1000)  NULL,
    [InventoryItemID]                    INT             NULL,
    [InventoryItemCode]                  VARCHAR (1000)  NULL,
    [InventoryItemDescription]           VARCHAR (1000)  NULL,
    [Barcode]                            VARCHAR (1000)  NULL,
    [InventorySiteID]                    INT             NULL,
    [InventorySiteDescription]           VARCHAR (1000)  NULL,
    [TransactionTypeID]                  INT             NULL,
    [TransactionTypeDescription]         VARCHAR (1000)  NULL,
    [TransactionSubTypeID]               INT             NULL,
    [TransactionSubTypeDescription]      VARCHAR (1000)  NULL,
    [LocationID]                         INT             NULL,
    [LocationDescription]                VARCHAR (1000)  NULL,
    [WarehouseID]                        INT             NULL,
    [WarehouseDescription]               VARCHAR (1000)  NULL,
    [DepositorID]                        INT             NULL,
    [DepositorDescription]               VARCHAR (1000)  NULL,
    [WarehouseReceiptID]                 INT             NULL,
    [WarehouseReceiptDescription]        VARCHAR (1000)  NULL,
    [ReceiptID]                          INT             NULL,
    [ReceiptDescription]                 VARCHAR (1000)  NULL,
    [EntryDateTime]                      VARCHAR (1000)  NULL,
    [EntryDateTime_Start]                VARCHAR (1000)  NULL,
    [EntryDateTime_End]                  VARCHAR (1000)  NULL,
    [TransactionStartDate]               VARCHAR (1000)  NULL,
    [TransactionStartDate_Start]         VARCHAR (1000)  NULL,
    [TransactionStartDate_End]           VARCHAR (1000)  NULL,
    [TransactionFinishDate]              VARCHAR (1000)  NULL,
    [TransactionFinishDate_Start]        VARCHAR (1000)  NULL,
    [TransactionFinishDate_End]          VARCHAR (1000)  NULL,
    [Host]                               VARCHAR (1000)  NULL,
    [Session]                            VARCHAR (1000)  NULL,
    [ProductionOrderID]                  INT             NULL,
    [ProductionOrderDescription]         VARCHAR (1000)  NULL,
    [ReceiptItemID]                      INT             NULL,
    [ShipmentID]                         INT             NULL,
    [ShipmentDescription]                VARCHAR (1000)  NULL,
    [ShipmentItemID]                     INT             NULL,
    [WarehouseOrderID]                   INT             NULL,
    [WarehouseOrderDescription]          VARCHAR (1000)  NULL,
    [WarehouseOrderDetailID]             INT             NULL,
    [WarehouseReceiptDetailID]           INT             NULL,
    [ProductionOrderDetailID]            INT             NULL,
    [ProductionOrderDetailDescription]   VARCHAR (1000)  NULL,
    [CountPlanRevisionID]                INT             NULL,
    [CountPlanRevisionDescription]       VARCHAR (1000)  NULL,
    [Canceled]                           BIT             NULL,
    [CuInventoryItemPackTypeID]          INT             NULL,
    [CuInventoryItemPackTypeDescription] VARCHAR (1000)  NULL,
    [InventoryItemPackTypeID]            INT             NULL,
    [InventoryItemPackTypeDescription]   VARCHAR (1000)  NULL,
    [LotBatchNo]                         VARCHAR (1000)  NULL,
    [ProductionDate]                     VARCHAR (1000)  NULL,
    [ProductionDate_Start]               VARCHAR (1000)  NULL,
    [ProductionDate_End]                 VARCHAR (1000)  NULL,
    [ExpireDate]                         VARCHAR (1000)  NULL,
    [ExpireDate_Start]                   VARCHAR (1000)  NULL,
    [ExpireDate_End]                     VARCHAR (1000)  NULL,
    [ReferanceNo]                        VARCHAR (1000)  NULL,
    [StockKitCode]                       VARCHAR (1000)  NULL,
    [StockId]                            VARCHAR (1000)  NULL,
    [ProjectID]                          INT             NULL,
    [ProjectDescription]                 VARCHAR (1000)  NULL,
    [CustomerID]                         INT             NULL,
    [CustomerDescription]                VARCHAR (1000)  NULL,
    [TransactionHistPalletID]            INT             NULL,
    [TransactionHistPalletDescription]   VARCHAR (1000)  NULL,
    [Quantity]                           NUMERIC (19, 5) NULL,
    [WarehouseReceiptSupplierID]         INT             NULL,
    [WarehouseReceiptSupplierCode]       VARCHAR (1000)  NULL,
    [OrderCustomerID]                    INT             NULL,
    [OrderCustomerCode]                  VARCHAR (1000)  NULL,
    [QuarantineResaonID]                 INT             NULL,
    [QuarantineResaonDescription]        VARCHAR (1000)  NULL,
    [SuitabilityReasonID]                INT             NULL,
    [SuitabilityReasonDescription]       VARCHAR (1000)  NULL,
    [FreeAttr1]                          VARCHAR (1000)  NULL,
    [FreeAttr2]                          VARCHAR (1000)  NULL,
    [FreeAttr3]                          VARCHAR (1000)  NULL,
    [PackedQuantity]                     NUMERIC (19, 5) NULL,
    [LocationDisplayMember]              VARCHAR (1000)  NULL,
    [HistoryId]                          VARCHAR (1000)  NULL,
    [WarehouseOrderType]                 VARCHAR (1000)  NULL,
    [WarehouseOrderTypeCode]             VARCHAR (1000)  NULL,
    [WarehouseOrderTypeID]               INT             NULL,
    [PageSize]                           INT             NULL,
    [SelectedPageIndex]                  INT             NULL,
    [PageCount]                          INT             NULL,
    [RecordCount]                        INT             NULL,
    PRIMARY KEY CLUSTERED ([TransactionHistoryID] ASC)
);

