CREATE PROCEDURE WRHS_insListOrders_Details(
    @ID INT,
    @Code VARCHAR(1000),
    @InventoryItemID INT,
    @InventoryItemDescription VARCHAR(1000),
    @InventoryItemInfo VARCHAR(1000),
    @Barcode VARCHAR(1000),
    @DisplayMember VARCHAR(1000),
    @InventoryItemPackTypeID INT,
    @InventoryItemPackTypeDescription VARCHAR(1000),
    @PackQuantity NUMERIC(19, 5),
    @WarehouseOrderID INT,
    @UnitWeight NUMERIC(19, 5),
    @UnitVolume NUMERIC(19, 5),
    @PACKIIPT_UnitWeight NUMERIC(19, 5),
    @AllocatedCuQuantity NUMERIC(19, 5),
    @PickedCuQuantity NUMERIC(19, 5),
    @LoadedCuQuantity NUMERIC(19, 5),
    @ShippedCuQuantity NUMERIC(19, 5),
    @PlannedPackQuantity NUMERIC(19, 5),
    @PlannedCuQuantity NUMERIC(19, 5),
    @SortedCUQuantity NUMERIC(19, 5),
    @PackedCUQuantity NUMERIC(19, 5),
    @CancelledCuQuantity NUMERIC(19, 5),
    @FreeAttr1 VARCHAR(1000),
    @FreeAttr2 VARCHAR(1000),
    @FreeAttr3 VARCHAR(1000),
    @CurrencyPrice NUMERIC(19, 5),
    @TaxRate NUMERIC(19, 5),
    @NetCurrencyPrice NUMERIC(19, 5),
    @TotalWeight NUMERIC(19, 5),
    @TotalVolume NUMERIC(19, 5),
    @LineWeight NUMERIC(19, 5),
    @SupplierID NUMERIC(19, 5),
    @SupplierDescription VARCHAR(1000),
    @Notes1 VARCHAR(1000),
    @SalesUnitPrice NUMERIC(19, 5),
    @ChannelOrderDetailCode VARCHAR(1000),
    @Errors VARCHAR(1000),
    @Success BIT,
    @SuccessMessage VARCHAR(1000),
    @IsExcelExport BIT,
    @PageSize INT,
    @SelectedPageIndex INT,
    @PageCount INT,
    @RecordCount INT
)
AS
BEGIN
	INSERT INTO ListOrders_Details(
    [ID],
    [Code] ,
    [InventoryItemID],
    [InventoryItemDescription] ,
    [InventoryItemInfo] ,
    [Barcode] ,
    [DisplayMember] ,
    [InventoryItemPackTypeID],
    [InventoryItemPackTypeDescription] ,
    [PackQuantity] ,
    [WarehouseOrderID],
    [UnitWeight] ,
    [UnitVolume] ,
    [PACKIIPT_UnitWeight] ,
    [AllocatedCuQuantity] ,
    [PickedCuQuantity] ,
    [LoadedCuQuantity] ,
    [ShippedCuQuantity] ,
    [PlannedPackQuantity] ,
    [PlannedCuQuantity] ,
    [SortedCUQuantity] ,
    [PackedCUQuantity] ,
    [CancelledCuQuantity] ,
    [FreeAttr1] ,
    [FreeAttr2] ,
    [FreeAttr3] ,
    [CurrencyPrice] ,
    [TaxRate] ,
    [NetCurrencyPrice] ,
    [TotalWeight] ,
    [TotalVolume] ,
    [LineWeight] ,
    [SupplierID] ,
    [SupplierDescription] ,
    [Notes1] ,
    [SalesUnitPrice] ,
    [ChannelOrderDetailCode] ,
    [Errors] ,
    [Success] ,
    [SuccessMessage] ,
    [IsExcelExport] ,
    [PageSize],
    [SelectedPageIndex],
    [PageCount],
    [RecordCount]
	)
SELECT 
    @ID ,
    @Code ,
    @InventoryItemID ,
    @InventoryItemDescription ,
    @InventoryItemInfo ,
    @Barcode ,
    @DisplayMember ,
    @InventoryItemPackTypeID ,
    @InventoryItemPackTypeDescription ,
    @PackQuantity ,
    @WarehouseOrderID ,
    @UnitWeight ,
    @UnitVolume ,
    @PACKIIPT_UnitWeight ,
    @AllocatedCuQuantity ,
    @PickedCuQuantity ,
    @LoadedCuQuantity ,
    @ShippedCuQuantity ,
    @PlannedPackQuantity ,
    @PlannedCuQuantity ,
    @SortedCUQuantity ,
    @PackedCUQuantity ,
    @CancelledCuQuantity ,
    @FreeAttr1 ,
    @FreeAttr2 ,
    @FreeAttr3 ,
    @CurrencyPrice ,
    @TaxRate ,
    @NetCurrencyPrice ,
    @TotalWeight ,
    @TotalVolume ,
    @LineWeight ,
    @SupplierID ,
    @SupplierDescription ,
    @Notes1 ,
    @SalesUnitPrice ,
    @ChannelOrderDetailCode ,
    @Errors ,
    @Success ,
    @SuccessMessage ,
    @IsExcelExport ,
    @PageSize ,
    @SelectedPageIndex ,
    @PageCount ,
    @RecordCount 
END